### ISSUE TITLE
UUID instead simple ID

### ISSUE THREAD

**Issue by MurMurt** [motivation-zone/db-service#2]
Предлагаю использовать uuid вместо id.
[Documentation](https://postgrespro.ru/docs/postgrespro/9.5/datatype-uuid)
https://github.com/motivation-zone/db-service/blob/a8416c135df6640c3bd2a1443eb7b9eceb13da11/migration/user.pgsql#L2

**Comment by dondiego4697** [comment]
исправлено везде
